// Mock 应用数据
export const apps = [
  {
    id: 'app-001',
    name: '企业审批助手',
    icon: 'https://api.dicebear.com/7.x/identicon/svg?seed=app1',
    owner: '张三',
    role: 'Owner',
    latestUpdate: '昨天更新了 API 配置',
    status: 'published',
    boundEAMAP: 'EAMAP-2024-001',
  },
  {
    id: 'app-002',
    name: '智能客服机器人',
    icon: 'https://api.dicebear.com/7.x/identicon/svg?seed=app2',
    owner: '李四',
    role: '开发者',
    latestUpdate: '今天添加了新能力',
    status: 'published',
    boundEAMAP: 'EAMAP-2024-002',
  },
  {
    id: 'app-003',
    name: '会议管理系统',
    icon: 'https://api.dicebear.com/7.x/identicon/svg?seed=app3',
    owner: '王五',
    role: '管理员',
    latestUpdate: '3 天前发布了新版本',
    status: 'published',
    boundEAMAP: 'EAMAP-2024-003',
  },
  {
    id: 'app-004',
    name: '文档协作工具',
    icon: 'https://api.dicebear.com/7.x/identicon/svg?seed=app4',
    owner: '赵六',
    role: 'Owner',
    latestUpdate: '本周进行了功能优化',
    status: 'published',
    boundEAMAP: 'EAMAP-2024-004',
  },
  {
    id: 'app-005',
    name: '数据分析平台',
    icon: 'https://api.dicebear.com/7.x/identicon/svg?seed=app5',
    owner: '钱七',
    role: '开发者',
    latestUpdate: '正在开发中',
    status: 'developing',
    boundEAMAP: 'EAMAP-2024-005',
  },
  {
    id: 'app-006',
    name: '员工考勤系统',
    icon: 'https://api.dicebear.com/7.x/identicon/svg?seed=app6',
    owner: '孙八',
    role: 'Owner',
    latestUpdate: '昨天配置了事件订阅',
    status: 'published',
    boundEAMAP: 'EAMAP-2024-006',
  },
  {
    id: 'app-007',
    name: '项目管理工具',
    icon: 'https://api.dicebear.com/7.x/identicon/svg?seed=app7',
    owner: '周九',
    role: '管理员',
    latestUpdate: '刚刚创建',
    status: 'developing',
    boundEAMAP: null,
  },
  {
    id: 'app-008',
    name: '知识库管理系统',
    icon: 'https://api.dicebear.com/7.x/identicon/svg?seed=app8',
    owner: '吴十',
    role: '开发者',
    latestUpdate: '正在开发中',
    status: 'developing',
    boundEAMAP: null,
  },
]

export default apps
