server:
  port: 18082

spring:
  redis:
    cluster:
      nodes:
        - 192.168.3.201:6379
        - 192.168.3.202:6379
        - 192.168.3.203:6379
        - 192.168.3.204:6379
        - 192.168.3.205:6379
      max-redirects: 3
    password: ${REDIS_PASSWORD:changeme}
    database: 1
    timeout: 5000ms
    lettuce:
      pool:
        max-active: 20
        max-wait: -1ms
        max-idle: 10
        min-idle: 5

api-server:
  url: ${API_SERVER_URL:http://api-server:18081}

internal:
  message-gateway:
    url: ${INTERNAL_MESSAGE_GATEWAY_URL:http://internal-message-gateway:9091}

mock:
  enabled: false

logging:
  level:
    root: INFO
    com.xxx.event: INFO
