// Mock API 数据 - 25 个 API
export const apiList = [
  // 用户管理 API (5 个)
  {
    id: 'api-001',
    name: '获取用户信息',
    path: '/open-apis/user/v1/get',
    method: 'GET',
    description: '获取指定用户的详细信息，包括基本信息、部门、角色等',
    category: 'user',
    permissionStatus: 'granted',
    isRequired: true,
  },
  {
    id: 'api-002',
    name: '搜索用户',
    path: '/open-apis/user/v1/search',
    method: 'POST',
    description: '根据条件搜索用户列表，支持分页和排序',
    category: 'user',
    permissionStatus: 'granted',
    isRequired: false,
  },
  {
    id: 'api-003',
    name: '批量获取用户信息',
    path: '/open-apis/user/v1/batch_get',
    method: 'POST',
    description: '批量获取多个用户的详细信息',
    category: 'user',
    permissionStatus: 'not_granted',
    isRequired: false,
  },
  {
    id: 'api-004',
    name: '创建用户',
    path: '/open-apis/user/v1/create',
    method: 'POST',
    description: '创建新用户，支持自定义字段',
    category: 'user',
    permissionStatus: 'not_granted',
    isRequired: false,
  },
  {
    id: 'api-005',
    name: '更新用户信息',
    path: '/open-apis/user/v1/update',
    method: 'PUT',
    description: '更新指定用户的信息',
    category: 'user',
    permissionStatus: 'not_granted',
    isRequired: false,
  },
  
  // 消息推送 API (5 个)
  {
    id: 'api-006',
    name: '发送文本消息',
    path: '/open-apis/message/v1/send_text',
    method: 'POST',
    description: '向用户或群组发送文本消息',
    category: 'message',
    permissionStatus: 'granted',
    isRequired: true,
  },
  {
    id: 'api-007',
    name: '发送卡片消息',
    path: '/open-apis/message/v1/send_card',
    method: 'POST',
    description: '发送交互式卡片消息，支持按钮、表单等元素',
    category: 'message',
    permissionStatus: 'granted',
    isRequired: false,
  },
  {
    id: 'api-008',
    name: '发送图片消息',
    path: '/open-apis/message/v1/send_image',
    method: 'POST',
    description: '发送图片消息',
    category: 'message',
    permissionStatus: 'not_granted',
    isRequired: false,
  },
  {
    id: 'api-009',
    name: '批量发送消息',
    path: '/open-apis/message/v1/batch_send',
    method: 'POST',
    description: '批量发送消息给多个用户或群组',
    category: 'message',
    permissionStatus: 'not_granted',
    isRequired: false,
  },
  {
    id: 'api-010',
    name: '撤回消息',
    path: '/open-apis/message/v1/recall',
    method: 'POST',
    description: '撤回已发送的消息',
    category: 'message',
    permissionStatus: 'not_granted',
    isRequired: false,
  },
  
  // 日历会议 API (5 个)
  {
    id: 'api-011',
    name: '创建日历事件',
    path: '/open-apis/calendar/v1/create',
    method: 'POST',
    description: '创建新的日历事件或会议',
    category: 'calendar',
    permissionStatus: 'granted',
    isRequired: false,
  },
  {
    id: 'api-012',
    name: '获取日历事件列表',
    path: '/open-apis/calendar/v1/list',
    method: 'GET',
    description: '获取指定时间范围内的日历事件列表',
    category: 'calendar',
    permissionStatus: 'granted',
    isRequired: false,
  },
  {
    id: 'api-013',
    name: '更新日历事件',
    path: '/open-apis/calendar/v1/update',
    method: 'PUT',
    description: '更新已有日历事件的信息',
    category: 'calendar',
    permissionStatus: 'not_granted',
    isRequired: false,
  },
  {
    id: 'api-014',
    name: '删除日历事件',
    path: '/open-apis/calendar/v1/delete',
    method: 'DELETE',
    description: '删除指定的日历事件',
    category: 'calendar',
    permissionStatus: 'not_granted',
    isRequired: false,
  },
  {
    id: 'api-015',
    name: '获取会议室列表',
    path: '/open-apis/calendar/v1/rooms',
    method: 'GET',
    description: '获取可用会议室列表及预订状态',
    category: 'calendar',
    permissionStatus: 'not_granted',
    isRequired: false,
  },
  
  // 云文档 API (4 个)
  {
    id: 'api-016',
    name: '获取文档信息',
    path: '/open-apis/drive/v1/get',
    method: 'GET',
    description: '获取指定文档的详细信息',
    category: 'drive',
    permissionStatus: 'granted',
    isRequired: false,
  },
  {
    id: 'api-017',
    name: '创建文档',
    path: '/open-apis/drive/v1/create',
    method: 'POST',
    description: '创建新的云文档',
    category: 'drive',
    permissionStatus: 'not_granted',
    isRequired: false,
  },
  {
    id: 'api-018',
    name: '上传文件',
    path: '/open-apis/drive/v1/upload',
    method: 'POST',
    description: '上传文件到云文档',
    category: 'drive',
    permissionStatus: 'not_granted',
    isRequired: false,
  },
  {
    id: 'api-019',
    name: '分享文档',
    path: '/open-apis/drive/v1/share',
    method: 'POST',
    description: '分享文档给指定用户或群组',
    category: 'drive',
    permissionStatus: 'not_granted',
    isRequired: false,
  },
  
  // 审批 API (3 个)
  {
    id: 'api-020',
    name: '创建审批实例',
    path: '/open-apis/approval/v1/create',
    method: 'POST',
    description: '创建新的审批流程实例',
    category: 'approval',
    permissionStatus: 'granted',
    isRequired: false,
  },
  {
    id: 'api-021',
    name: '获取审批详情',
    path: '/open-apis/approval/v1/get',
    method: 'GET',
    description: '获取审批实例的详细信息和进度',
    category: 'approval',
    permissionStatus: 'granted',
    isRequired: false,
  },
  {
    id: 'api-022',
    name: '审批操作',
    path: '/open-apis/approval/v1/approve',
    method: 'POST',
    description: '对审批实例进行同意、拒绝等操作',
    category: 'approval',
    permissionStatus: 'not_granted',
    isRequired: false,
  },
  
  // 通讯录 API (3 个)
  {
    id: 'api-023',
    name: '获取部门列表',
    path: '/open-apis/contact/v1/departments',
    method: 'GET',
    description: '获取企业部门列表',
    category: 'contact',
    permissionStatus: 'granted',
    isRequired: true,
  },
  {
    id: 'api-024',
    name: '获取部门成员',
    path: '/open-apis/contact/v1/department_users',
    method: 'GET',
    description: '获取指定部门的成员列表',
    category: 'contact',
    permissionStatus: 'granted',
    isRequired: false,
  },
  {
    id: 'api-025',
    name: '获取企业成员列表',
    path: '/open-apis/contact/v1/users',
    method: 'GET',
    description: '获取企业所有成员列表',
    category: 'contact',
    permissionStatus: 'not_granted',
    isRequired: false,
  },
]

// API 分类
export const apiCategories = [
  { value: 'all', label: '全部 API' },
  { value: 'user', label: '用户管理' },
  { value: 'message', label: '消息推送' },
  { value: 'calendar', label: '日历会议' },
  { value: 'drive', label: '云文档' },
  { value: 'approval', label: '审批' },
  { value: 'contact', label: '通讯录' },
]

export default { apiList, apiCategories }
